name: Enforce Pull Request for Large Changes

on:
  push:
    branches:
      - test_1
      - test_2

jobs:
  enforce-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get number of lines changed
        id: lines-changed
        run: |
          lines_changed=$(git diff --numstat ${{ github.event.before }} ${{ github.sha }} | awk '{ total += $1 + $2 } END { print total }')
          echo "Lines changed: $lines_changed"
          echo "::set-output name=lines_changed::$lines_changed"

      - name: Check if pull request is needed
        id: check-pr-needed
        run: |
          lines_changed=${{ steps.lines-changed.outputs.lines_changed }}
          threshold=30  # Adjust the threshold as needed
          if [ -n "$lines_changed" ] && [ "$lines_changed" -gt "$threshold" ]; then
            echo "::set-output name=pr_needed::true"
          else
            echo "::set-output name=pr_needed::false"
          fi

      - name: Comment on pull request if push was blocked
        if: steps.check-pr-needed.outputs.pr_needed == 'true'
        run: |
          echo "::error::Push was blocked. Please create a pull request for large changes."
