name: Enforce Pull Request for Large Changes on Non-Main Branches

on:
  push:
    branches-ignore:
      - main  # Exclude the main branch

jobs:
  check_large_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check for large push
        id: lines_changed
        run: |
          git fetch origin ${{ github.event.before }}:${{ github.event.before }}
          LINES_ADDED=$(git diff --numstat ${{ github.event.before }} | awk '{s+=$1} END {print s}')
          LINES_DELETED=$(git diff --numstat ${{ github.event.before }} | awk '{s+=$2} END {print s}')
          TOTAL_LINES=$((LINES_ADDED + LINES_DELETED))
          echo "Total lines changed: $TOTAL_LINES"
          if [ "$TOTAL_LINES" -gt 30 ]; then
            echo "##[error] Push contains more than 30 lines of changes. Please submit a pull request for review."
            exit 1
          fi

      - name: Push is acceptable
        if: steps.lines_changed.outcome == 'success'
        run: echo "Push contains fewer than 30 lines of changes."
